name: Scheduled Update
on:
    schedule:
        - cron: "0/30 * * * *"
    workflow_dispatch: # Allow manual triggering

permissions:
    contents: write
    issues: read

jobs:
    generate-rss:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v6
              with:
                  python-version: "3.10"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: Generate RSS feed
              run: |
                  python _python/rss_dotnet.py
                  python _python/rss_insurance.py
                  python _python/rss_secops.py

              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Commit and push
              run: |-
                  git diff
                  git config user.name "GitHub Action"
                  git config user.email "action@github.com"
                  git diff --quiet || (git add -A && git commit -m "New Feed")
                  git push
